package returngift;

public class ColorDesign {
	
	public static void setSearchFeedbackDesign() {
		
		AppUI.lblGender.setForeground(AppUI.choco_brown);
		AppUI.lblAge.setForeground(AppUI.choco_brown);
		AppUI.lblPersonality.setForeground(AppUI.choco_brown);
		AppUI.lblInterests.setForeground(AppUI.choco_brown);
		AppUI.lblOccasion.setForeground(AppUI.choco_brown);
		AppUI.lblRelationshipLevel.setForeground(AppUI.choco_brown);
		AppUI.lblCreativityLevel.setForeground(AppUI.choco_brown);
		AppUI.lblColor.setForeground(AppUI.choco_brown);
		AppUI.lblPriceRange.setForeground(AppUI.choco_brown);
		AppUI.lblFeedback.setForeground(AppUI.choco_brown);
		AppUI.lblRating.setForeground(AppUI.choco_brown);
		AppUI.account.setForeground(AppUI.choco_brown);
		AppUI.search.setForeground(AppUI.choco_brown);
		AppUI.browser.setForeground(AppUI.choco_brown);
		AppUI.personalitytest.setForeground(AppUI.choco_brown);
		AppUI.forum.setForeground(AppUI.choco_brown);
		AppUI.feedback.setForeground(AppUI.choco_brown);
		AppUI.gendercombo.setForeground(AppUI.choco_brown);
		AppUI.agecombo.setForeground(AppUI.choco_brown);
		AppUI.personalitycombo.setForeground(AppUI.choco_brown);
		AppUI.occasioncombo.setForeground(AppUI.choco_brown);
		AppUI.colorcombo.setForeground(AppUI.choco_brown);
		AppUI.ratingcombo.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_1.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_2.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_3.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_4.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_5.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_6.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_7.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_8.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_9.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_10.setForeground(AppUI.choco_brown);
		AppUI.chckbxInterest_11.setForeground(AppUI.choco_brown);
		AppUI.btnResearch.setForeground(AppUI.choco_brown);
		AppUI.btnSearch.setForeground(AppUI.choco_brown);
		AppUI.btnSendFeedback.setForeground(AppUI.choco_brown);
		AppUI.btnRandomize.setForeground(AppUI.choco_brown);
		AppUI.btnBack.setForeground(AppUI.choco_brown);
		AppUI.btnForward.setForeground(AppUI.choco_brown);
		AppUI.rlevelslider.setForeground(AppUI.choco_brown);
		AppUI.clevelslider.setForeground(AppUI.choco_brown);
		AppUI.pricerangeslider.setForeground(AppUI.choco_brown);
		AppUI.feedbacktextarea.setForeground(AppUI.choco_brown);

		AppUI.account.setBackground(AppUI.light_bluish_gray);
		AppUI.search.setBackground(AppUI.light_bluish_gray);
		AppUI.browser.setBackground(AppUI.light_bluish_gray);
		AppUI.personalitytest.setBackground(AppUI.light_bluish_gray);
		AppUI.forum.setBackground(AppUI.light_bluish_gray);
		AppUI.feedback.setBackground(AppUI.light_bluish_gray);
		AppUI.gendercombo.setBackground(AppUI.pinkish_beige);
		AppUI.agecombo.setBackground(AppUI.pinkish_beige);
		AppUI.personalitycombo.setBackground(AppUI.pinkish_beige);
		AppUI.occasioncombo.setBackground(AppUI.pinkish_beige);
		AppUI.colorcombo.setBackground(AppUI.pinkish_beige);
		AppUI.ratingcombo.setBackground(AppUI.pinkish_beige);
		AppUI.chckbxInterest.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_1.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_2.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_3.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_4.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_5.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_6.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_7.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_8.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_9.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_10.setBackground(AppUI.light_bluish_gray);
		AppUI.chckbxInterest_11.setBackground(AppUI.light_bluish_gray);
		AppUI.btnResearch.setBackground(AppUI.milky_cocoa);
		AppUI.btnSearch.setBackground(AppUI.milky_cocoa);
		AppUI.btnSendFeedback.setBackground(AppUI.milky_cocoa);
		AppUI.btnRandomize.setBackground(AppUI.milky_cocoa);
		AppUI.btnBack.setBackground(AppUI.milky_cocoa);
		AppUI.btnForward.setBackground(AppUI.milky_cocoa);
		AppUI.rlevelslider.setBackground(AppUI.light_bluish_gray);
		AppUI.clevelslider.setBackground(AppUI.light_bluish_gray);
		AppUI.pricerangeslider.setBackground(AppUI.light_bluish_gray);
		AppUI.feedbacktextarea.setBackground(AppUI.pinkish_beige);
		AppUI.editorpane.setBackground(AppUI.pinkish_beige);
		
		
		
	}
	
	public static void setTestDesign() {
		

		PersonalityTest.btnSubmit.setForeground(AppUI.choco_brown);
		PersonalityTest.btnSubmit.setBackground(AppUI.pinkish_beige);
		PersonalityTest.btnInfo.setForeground(AppUI.choco_brown);
		PersonalityTest.btnInfo.setBackground(AppUI.milky_cocoa);
		PersonalityTest.textfield.setForeground(AppUI.choco_brown);
		PersonalityTest.textfield.setBackground(AppUI.pinkish_beige);

		PersonalityTest.lblNewLabel.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_1.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_2.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_3.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_4.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_5.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_6.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_7.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_8.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_9.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_10.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_11.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_12.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_13.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_14.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_15.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_16.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_17.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_18.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_19.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_20.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_21.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_22.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_23.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_24.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_25.setForeground(AppUI.choco_brown);
		PersonalityTest.lblNewLabel_26.setForeground(AppUI.choco_brown);
		PersonalityTest.lblPersonality_1.setForeground(AppUI.choco_brown);

		PersonalityTest.rdbtnNewRadioButton.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_1.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_2.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_3.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_4.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_5.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_6.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_7.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_8.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_9.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_10.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_11.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_12.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_13.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_14.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_15.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_16.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_17.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_18.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_39.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_19.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_20.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_21.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_22.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_23.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_24.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_25.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_26.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_27.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_28.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_29.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_30.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_31.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_32.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_33.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_34.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_35.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_36.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_37.setForeground(AppUI.choco_brown);
		PersonalityTest.rdbtnNewRadioButton_38.setForeground(AppUI.choco_brown);

		PersonalityTest.rdbtnNewRadioButton.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_1.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_2.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_3.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_4.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_5.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_6.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_7.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_8.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_9.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_10.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_11.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_12.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_13.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_14.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_15.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_16.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_17.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_18.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_39.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_19.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_20.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_21.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_22.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_23.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_24.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_25.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_26.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_27.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_28.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_29.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_30.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_31.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_32.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_33.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_34.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_35.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_36.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_37.setBackground(AppUI.light_bluish_gray);
		PersonalityTest.rdbtnNewRadioButton_38.setBackground(AppUI.light_bluish_gray);
		
	}

}
